### ISSUE TITLE
关于.pyc会被识别成.py

### ISSUE THREAD

**Issue by LiuXianBang** [LuckyHookin/copyt#1]
程序存在bug，这是我的软件运行截图
![image](https://user-images.githubusercontent.com/13533545/153191380-a0af9b15-93d5-400d-bb8c-b85350103532.png)
希望能修复

**Comment by LuckyHookin** [comment]
@382009 抱歉，这么久才回复你。如你的截图所示，在 `.py|.json|` 中最后有一个 `|`，这个 `|` 代表 ”或“ 的意思，也就是说，
`.py|.json|` 表示：

匹配 ".py" 或 ”.json“ 或 ”“。其中 ”“ 是空字符串，可以匹配任意的文件类型。

按你的想法，只要用 `.py|.json` 就可以了。
